// Enter your thesis data here:
#let titleEnglish = "One-Click Deployment"
#let subTitleEnglish = "Simplifying Open-Source Software Deployment"
#let degree = "Bachelor"
#let program = "BsC Computer Science"
#let advisor = "Erik Graf"
#let expert = "Reto Tinkeler"
#let author = "Jan Lauber"
#let submissionDate = "13.06.2024"
#let projectPartner = "Natron Tech AG"